### ISSUE TITLE
Tu de brincation with me?

### ISSUE THREAD

**Issue by sergiors** [haskellcamargo/gemidao-do-zap#1]

**Comment by haskellcamargo** [comment]
![Why?](https://user-images.githubusercontent.com/7553006/29043990-c31d932a-7b93-11e7-8287-c469b32abee5.png)

**Comment by williamrozin** [comment]
best repo 2017

**Comment by brenohq** [comment]
:star: star aqui também pq uma só tá pouco :star:

**Comment by rmrgh** [comment]
top trending nodeJS 2017 on github

**Comment by raisiqueira** [comment]
Aguardando.... 😅

**Comment by OtacilioN** [comment]
Velhoooo, eu quero muito usar esse troço, como coloca créditos nesse total voice??

**Comment by andrescalco** [comment]
EHAUEHAUHUEHAUEH sensacional!

Agora preciso escolher calmamente 9 pessoas, pois já foi uma de testes.

**Comment by OtacilioN** [comment]
FUNCIONOUUUUUUUuuu! Senhores esperem um certo tempo que entra os 3 reais, mano isso é muito divertido, puta merda!

**Comment by bcarvalho89** [comment]
Ducarai!!!!
Mas debitou R$0,35 por chamada de mim :(

**Comment by ealbuquerque** [comment]
hahahahhahahah, sensacional!

**Comment by OtacilioN** [comment]
@bcarvalho89  é a inflação!

**Comment by OtacilioN** [comment]
Galera, agora vamos lembrar de usar esse serviço somente para o bem tá coleguinhas? Nada de mandar gemidão do zap pro chefe com o número do coleguinha de trabalho que você não gosta.

**Comment by annielmenezes** [comment]
@OtacilioN porque dar uma ideia dessa cara? ashuashaushaushaus

**Comment by klaygomes** [comment]
puta que pariu. mandar um para o meu antigo chefe hahahahahha

**Comment by sergiors** [comment]
minha issue bombou kkkk

**Comment by OtacilioN** [comment]
Tô só esperando mandarem aqui listas de deputados, mandar o Jean Willis pro Bolsonaro e vice e versa.

**Comment by OtacilioN** [comment]
@sergiors melhor título de Issue BR Ever, e como a gente é BR tamo fazendo isso aqui de chat mesmo porque foda-se.

**Comment by ricardorohde** [comment]
como roda? :/

**Comment by sergiors** [comment]
> Tô só esperando mandarem aqui listas de deputados, mandar o Jean Willis pro Bolsonaro e vice e versa.

esse fera

**Comment by andrescalco** [comment]
@OtacilioN http://www2.camara.leg.br/deputados/pesquisa

**Comment by OtacilioN** [comment]
Não pode C @andrescalco, mas acho que esses números públicos eles não usam.

**Comment by rubenmarcus** [comment]
mas tem que validar o numero do celular, se não eu iria fazer um bot, e colocaria todos os numeros de call center, e de cobrança de banco que eu sei aqui, e ia deixar o dia inteiro rodando kk

**Comment by fabiomirandaa** [comment]
Vou criar outra conta no github só pra dar mais uma star.

**Comment by haskellcamargo** [comment]
Enquanto isso nos _tickets_ da TotalVoice:

![image](https://user-images.githubusercontent.com/7553006/29088063-688b94c8-7c4e-11e7-9685-9e5e15ef39ef.png)

**Comment by sayhicoelho** [comment]
Quanto tempo leva pra eu receber meus 3 conto? A mão chega a tremer pra trolar uns abiguinhos aqui...

**Comment by hadiljr** [comment]
Ta de parabéns ! HueHue 🥇

**Comment by githubdoramon** [comment]
Mano.... esse repositório é a prova que o mundo ainda tem esperança

**Comment by ghost** [comment]
Parabens Velho, mto massa \o/

**Comment by fernandomoraes** [comment]
Doação de tokens:
24746bfa52d3f59f4bfb8aab54a08e1d
90fbf7d3d31821ab2608b78ce83a5153
e831f2cf8ddfd52e49048e054e21b674
3a6c4729e17ebeb8937033c15e92ecf0

**Comment by haskellcamargo** [comment]
Parabéns, vocês colocaram o *Gemidão do Zap* nos trends mundiais do Github de hoje, ultrapassando até projetos como React, Vue, Webpack, React Native e Bootstrap!

![2017-08-08-165012_1134x614_scrot](https://user-images.githubusercontent.com/7553006/29091608-e8f568a4-7c59-11e7-9c04-35a3d0fef238.png)

**Comment by danielmadu** [comment]
Não sei como a internet sobreviveu até hj sem esse repo. O melhor do ano. Parabéns

**Comment by admirschaurich** [comment]
Tentando usar aqui, mas quando executo, gera essa exception:
`SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\~~~~~~\AppData\Roaming\npm\node_modules\gemidao-do-zap\node_modules\yargs\lib\command.js:3:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)`

Alguém passou por isso tbem?

**Comment by sayhicoelho** [comment]
Atendi a ligação mas não ouvi o gemidão; qual é o procedimento com o .mp3?

**Comment by haskellcamargo** [comment]
@admirschaurich, atualiza sua versão do NodeJS :smile:

**Comment by haskellcamargo** [comment]
@renandiett normalmente é instabilidade na rede da TotalVoice, é raro, mas possível.

**Comment by vctrmagno** [comment]
Melhor projeto do github, hahahaha. Me divertindo demais! Parabéns @haskellcamargo !!!

**Comment by admirschaurich** [comment]
@haskellcamargo Atualizei o node, removi e reinstalei o gemidao-do-zap, mas o erro continua o mesmo.
Mais alguma dica?

**Comment by didiraja** [comment]
mano ta de parabens hauhaua pra quem reclamava que o brasil não figurava no top10 do github

**Comment by sayhicoelho** [comment]
CRLH PESSOAL! ESSA PORRA FUNCIONA! kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkjjjjjj

**Comment by emanuelhfarias** [comment]
@haskellcamargo mito.

**Comment by santiagomarcos** [comment]
@haskellcamargo  funciona mesmo  hahahahaha! quase acabei com o casamento dos meus tios com isso! minha tia achou que meu tio tava traindo ela KKKKKKKKKKKKKKKKKKKKKK

**Comment by ernani** [comment]
Tentei agora pegar o crédito de testes mas não tá rolando...rs Acho que floodaram o serviço.

**Comment by lucasmiqueias** [comment]
@ernani sim, não estão mais liberando os créditos. rs...

**Comment by ernani** [comment]
Tou quase pondo uns créditos eu mesmo kkk

**Comment by haskellcamargo** [comment]
Eu conversei com o CEO da TotalVoice. Até agora, ele não me falou de modificações no serviço. Aparentemente, só está sobrecarregado. Esperem algumas horas que o crédito cai, calma.

**Comment by lucasdamo** [comment]
Como que funciona esse serviço totalvoice ? Como que ele consegue ligar para as pessoas com o numero que você quiser ?

**Comment by OtacilioN** [comment]
É só esperar que dá tudo certo, @haskellcamargo, bixo você revolucionou o conceito de Dev BR.

**Comment by GeoConstantino** [comment]
To tomando esse erro ao executar:
/usr/bin/env: ‘node’: No such file or directory
Não sei como proceder...

**Comment by haskellcamargo** [comment]
@GeoConstantino, instala o NodeJS aí.

**Comment by GeoConstantino** [comment]
Eu instalei mas não deu certo, mas consegui resolver usando isso:

ln -s /usr/bin/nodejs /usr/bin/node

Fiz um link simbolico!

**Comment by admirschaurich** [comment]
No windows não foi... mas instalei numa vm com ubuntu e tem um monte me xingando pelo zap... kkkkkkkkkkkkkk... Muiiiiito bom!!! Parabéns @haskellcamargo

**Comment by leonirlopes** [comment]
top, mas trolei a galera com curl mesmo

**Comment by sergiors** [comment]
AAAWN OOOWN NHAAA AWWWWN AAAAAH AAAWN OOOWN NHAAA AWWWWN AAAAAH

**Comment by ernani** [comment]
Ae! Tá rolando! Sensacional! isso pode virar um app com in app purchases!

**Comment by haskellcamargo** [comment]
Gente, pra quem tá com problema com o crédito: contas criadas à noite não recebem crédito para evitar spammers. Criem a conta de teste antes das 17:00.

**Comment by haskellcamargo** [comment]
Acabei de mandar um gemidão pro gabinete do Bolsonaro.

**Comment by ghost** [comment]
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk

**Comment by andrescalco** [comment]
Hahahahahahahahahahah

**Comment by ernani** [comment]
Eita, virou SAAS -> http://gemid.in/

**Comment by sergiors** [comment]
Olha esses feras 👏 👏 👏 👏 👏

**Comment by nosilex** [comment]
@haskellcamargo mito GitHub 2017!!!!!!!

**Comment by pedrohma** [comment]
Sensacional!

**Comment by sergiors** [comment]
AAAWN OOOWN NHAAA AWWWWN AAAAAH AAAWN OOOWN NHAAA AWWWWN AAAAAH AAAWN OOOWN NHAAA AWWWWN AAAAAH AAAWN OOOWN NHAAA AWWWWN AAAAAH AAAWN OOOWN NHAAA AWWWWN AAAAAH AAAWN OOOWN NHAAA AWWWWN AAAAAH
AAAWN OOOWN NHAAA AWWWWN AAAAAH AAAWN OOOWN NHAAA AWWWWN AAAAAH
AAAWN OOOWN NHAAA AWWWWN AAAAAH AAAWN OOOWN NHAAA AWWWWN AAAAAH
