### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by renatosarro** [haskellcamargo/gemidao-do-zap#19]
/usr/local/lib/node_modules/gemidao-do-zap/node_modules/yargs/node_modules/camelcase/index.js:4
	let isLastCharLower = false;
	^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gemidao-do-zap/node_modules/yargs/lib/command.js:3:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by cuchi** [comment]
Yep, é regra do linter.

Usa `const`

**Comment by haskellcamargo** [comment]
Versão do Node. Atualiza para 6+ :D

**Comment by renatosarro** [comment]
Boa! Foi :D
